#ifndef CONFIG_HPP
#define CONFIG_HPP

/* CONFIGURATION LISTED BELOW */

#define USE_LUA_ERROR_HANDLING
#define USE_LUA_DOFUNCTION
#define USE_LUA_HOOKS

/* CONFIGURATION LISTED ABOVE */

#endif /* CONFIG_HPP */
