#ifndef HTP_CONFIG_HPP
#define HTP_CONFIG_HPP

/* CONFIGURATION LISTED BELOW */

#define HTP_USE_LUA_ERROR_HANDLING
#define HTP_USE_LUA_DOFUNCTION
#define HTP_USE_LUA_HOOK

/* CONFIGURATION LISTED ABOVE */

#endif /* CONFIG_HPP */
